
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: dossier_dev
  username: josh
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: dossier_test
  username: josh
  password:

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: dossier_prod
  username: josh
  password: