
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: dossier_dev
  pool: 5
  username: josh
  password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: dossier_test
#   pool: 5
#   username: josh
#   password: